//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RescueNeeds.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public District()
        {
            this.CampInCharges = new HashSet<CampInCharge>();
            this.Camps = new HashSet<Camp>();
            this.Places = new HashSet<Place>();
        }
    
        public int DistrictID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CampInCharge> CampInCharges { get; set; }
        public virtual ICollection<Camp> Camps { get; set; }
        public virtual ICollection<Place> Places { get; set; }
    }
}
