//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RescueNeeds.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.CampRequirements = new HashSet<CampRequirement>();
        }
    
        public int ItemID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CampRequirement> CampRequirements { get; set; }
    }
}
