//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RescueNeeds.Service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RescueNeedsEntities : DbContext
    {
        public RescueNeedsEntities()
            : base("name=RescueNeedsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CampRequirement> CampRequirements { get; set; }
        public DbSet<Camp> Camps { get; set; }
        public DbSet<Discussion> Discussions { get; set; }
        public DbSet<District> Districts { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<Person> Persons { get; set; }
        public DbSet<Place> Places { get; set; }
        public DbSet<CampInCharge> CampInCharges { get; set; }
    }
}
