//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RescueNeeds.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public Place()
        {
            this.Camps = new HashSet<Camp>();
        }
    
        public int PlaceID { get; set; }
        public string Name { get; set; }
        public Nullable<int> DistrictID { get; set; }
    
        public virtual ICollection<Camp> Camps { get; set; }
        public virtual District District { get; set; }
    }
}
